spring:
  application:
    name: basket-service
  data:
    redis:
      caches:
        carts:
          ttl: PT24H
logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
