spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/onlinesushishop
    username: onlinesushishop
    password: Strong!Pass1@#
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
