services:
  postgres:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onlinesushishop
      - POSTGRES_USER=onlinesushishop
      - POSTGRES_PASSWORD=Strong!Pass1@#
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "pl.lukaskierzek.catalog.product.price-updated:1:1"
    networks:
      - kafka-net
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  gripmock:
    image: bavix/gripmock
    volumes:
      - ./gripmock/catalog.proto:/proto/catalog.proto:ro
      - ./gripmock/catalog.json:/stubs/catalog.json:ro
    command: |
      --stub=/stubs \
      --imports=/proto \
      /proto/catalog.proto
    ports:
      - "4770:4770"
      - "4771:4771"
networks:
  kafka-net:
    driver: bridge
