basePath: /api/v1/cart
definitions:
  handlers.putCartInput:
    description: PUT cart input
    properties:
      product_id:
        type: string
      quantity:
        type: integer
    required:
    - product_id
    - quantity
    type: object
  handlers.putCartRequest:
    description: PUT cart data
    properties:
      items:
        items:
          $ref: '#/definitions/handlers.putCartInput'
        type: array
    required:
    - items
    type: object
  models.Cart:
    description: Shopping cart information
    properties:
      cart_items:
        items:
          $ref: '#/definitions/models.CartItem'
        type: array
      id:
        type: string
      owner_id:
        type: string
      total_price:
        type: number
    type: object
  models.CartItem:
    description: Shopping cart item information
    properties:
      id:
        type: string
      price:
        type: number
      product_id:
        type: string
      quantity:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Shopping Cart API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Shopping Cart API
  version: "1.0"
paths:
  /:
    get:
      operationId: get-users-cart
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
      summary: get user's cart
    put:
      operationId: update-users-cart
      parameters:
      - description: put cart data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.putCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Cart'
      summary: update user's cart
swagger: "2.0"
